# Generated by Django 3.1.7 on 2022-01-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211006_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Very good'), (3, 'Not Good'), (4, 'Excellent'), (5, 'Ultra Excellent')]),
        ),
    ]
